# Generated by Django 3.2.8 on 2021-10-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
