# Generated by Django 3.2.8 on 2021-10-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subjects_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
